[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium>=1.1.1",
    "numpy>=2.2.6",
    "stable-baselines3[extra]>=2.6.0",
    "standard-imghdr>=3.13.0",
]
